### ISSUE TITLE
Mention that the canonical mode ensures that the actual markdown document (underlying code) is identical between visual and code view

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-advanced#100]

**Comment by AndersAskeland** [comment]
In relation to the text, is "Lists in Markdown must have an empty space above them to work properly." correct?

Is it not just that the visual mode has formatting based on that? Do you know @lwjohnst86 ? 

Rendering without an empty space gives the same result

**Comment by AndersAskeland** [comment]
Also, the text "Since this mode is on automatically, as we work through the sessions, we’ll get lots of experience using it." is not correct? Is it not only active for the lesson.qmd unless we add it to the _quarto.yml (or GUI options)?

**Comment by lwjohnst86** [comment]
You're right that rendering works when a list is right below a header. But a list right below a paragraph doesn't work. Same with other situations. So I just keep it simple and say "always have a space above a list". I can add that to the text.

And good point about the text on automatically... I'll update it
