### ISSUE TITLE
credentials::set_github_pat(TRUE) is not always allowed to read credentials

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-advanced#101]
My Mac does not allow the function to read my git creds and manually asks for a new token.

**Comment by AndersAskeland** [comment]
Could potentially cause problems during the course.

Potential solutions:

* Run renv::deactivate() before opening the survey
* Setup new GitHub PAT using usethis::create_github_token()

**Comment by lwjohnst86** [comment]
Hmm, looks like this is no longer necessary if we use gitcreds. Which we do. So I will remove the credentials text.
