### ISSUE TITLE
Bug: '! invalid version specification ‘v1’ error', when running renv::install() 

### ISSUE THREAD

**Issue by signekb** [rostools/r-cubed-advanced#112]
When running renv::install() in section 5.5, I get an error. Full error message: 

"Error:                                              
! error in pak subprocess
Caused by error: 
! invalid version specification ‘v1’"

It's specified in the introduction that we should write v1. However, my default was 0.0.1. 
https://github.com/rostools/r-cubed-advanced/blob/53e070d16d3039fd6947d88131060e5d895db968/sessions/introduction.qmd#L175-L179

**Comment by lwjohnst86** [comment]
Thanks for the catch!
