### ISSUE TITLE
Renv and pak

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-advanced#116]
Renv now uses the Posit package manager by default. I can't find out if the pak setting respects the usage of posit package manager, or if it goes back to CRAN?

**Comment by lwjohnst86** [comment]
I'm pretty sure pak respects PPM. It respected RSPM (RStudio version before renaming to PPM). We don't mention PPM anywhere, so I'll close this for now, unless someone brings it up and we can add a note/FAQ :relaxed:
