### ISSUE TITLE
Connecting to github, missing title

### ISSUE THREAD

**Issue by Isabellvse** [rostools/r-cubed-advanced#213]
I am going through the course material, following it step by step and in section 5.7 Exercise: Connect your project to GitHub, where you go to section 9.2 Linking your project to GitHub, and I run the code usethis::use_github(), I get this error: Fejl i val %||% default : Field 'Title' not found.

But if I add "Title: AdvancedR3" to the DESCRIPTION file, it runs no problem and creates a repository on my github.

**Comment by lwjohnst86** [comment]
Ugh, right. I fix this in prodigenr, but having submitted the update to CRAN yet. I'll put that information into the instructions... Thanks!! :star_struck:
