### ISSUE TITLE
Should we use namespaces in `_targets.R`

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-advanced#227]
We have a step where we define packages used for the target pipeline (see below).

"It probably won’t run though. That’s because [targets](https://docs.ropensci.org/targets/) doesn’t know about the packages that you need for the pipeline. To add it, we need to go to the tar_option_set() section of the _targets.R file and add to the packages = c("tibble") code with the packages we use that aren’t explicitly called via :: (e.g. |>). For now, we only need to add "dplyr" to the packages argument."

However, because we currently use namespaces for the functions used inside the targets file (i.e. `readr::read_csv()`), this error will never trigger. What is the correct way?

**Comment by AndersAskeland** [comment]
Targets documentation says:

One limitation is that entire namespaced calls like package1::function_from_package1() are not registered in the dependency graph because of the limitations of the static code analysis capabilities of targets (powered by codetools::findGlobals()). tar_target(name = output, command = function_from_package1()) has a dependency function_from_package1(), but tar_target(name = output, command = package1::function_from_package1()) does not have a dependency package1::function_from_package1(). This is because :: is treated as a function with arguments package and function_from_package1.



What do you think @lwjohnst86 ?

**Comment by lwjohnst86** [comment]
Hmmm yea, I feel like I fixed that text... But yea, as long as we use `packagename::`, this won't be a problem! Maybe just remove that text then, it might cause more confusion than benefit.

**Comment by AndersAskeland** [comment]
I removed it in https://github.com/rostools/r-cubed-advanced/commit/c717cb290a6ef58ed874ce622597d88ba71f90cf, but unsure if there should be some callout note explaining different ways of defining packages.
