### ISSUE TITLE
Section 3.4 Installing the latest programs, minor correction

### ISSUE THREAD

**Issue by Isabellvse** [rostools/r-cubed-advanced#231]
For the installation guide on windows, 

(I could not find the "installing-programs.md" in my pull request to correct myself, so here it is): 

In section 3.4 Installing the latest programs I just have a minor correction:

"3:[Git](https://git-scm.com/download/win): Select the “Click here for download” link. Git is used throughout many sessions in the courses. When installing, it will ask for a selecting a “Text Editor” and while we won’t be using this in the course, Git needs to know this information so choose Notepad." 

on the website it is "Click here *to* download"

**Comment by lwjohnst86** [comment]
Done :)
