### ISSUE TITLE
7.5 - remove mutate from code

### ISSUE THREAD

**Issue by Isabellvse** [rostools/r-cubed-advanced#236]
the section which says
"Now add the new function above the pivot_wider() code in the doc/learning.qmd file."

lipidomics_wide <- lipidomics |>
  column_values_to_snake_case(metabolite) |>
  mutate(metabolite = snakecase::to_snake_case(metabolite)) |>
  pivot_wider(
    names_from = metabolite,
    values_from = value,
    values_fn = mean,
    names_prefix = "metabolite_"
  )

we should remove the mutate part, because that is already in the column_values_to_snake_case(metabolite) :-) 
lipidomics_wide <- lipidomics |>
  column_values_to_snake_case(metabolite) |>
  pivot_wider(
    names_from = metabolite,
    values_from = value,
    values_fn = mean,
    names_prefix = "metabolite_"
  )

**Comment by AndersAskeland** [comment]
Fixed in #235
