### ISSUE TITLE
8.3 Apply logistic regression to each metabolite

### ISSUE THREAD

**Issue by ben-stocks1** [rostools/r-cubed-advanced#44]
Throughout 8.3 there is a typo in calling the function column_values_to_snake_case. the final underscore is missing such that it says column_values_to_snakecase

**Comment by ben-stocks1** [comment]
This isn't actually an issue - just a difference to how i wrote it in my code. So it was in fact my typo from the start. Sorry Luke!

**Comment by lwjohnst86** [comment]
haha thanks for the issue though! :grinning:
