### ISSUE TITLE
Extension issue on: check_project_setup_advanced

### ISSUE THREAD

**Issue by LuisMLealGarza** [rostools/r-cubed-advanced#91]
r3::check_project_setup_advanced() is likely to fail for everyone following the tasks.

The reason is that in line 9 on r3::check_project_setup_advanced, you ask for "lipidomics.rda", however, we save it as a ".csv".

Either add:
save(lipidomics,file=here::here("data/lipidomics.rda")) to  nmr-omics.R 
or
 change line 9 on r3::check_project_setup_advanced()  to: fs::file_exists(fs::path(proj, "data", "lipidomics.csv")))) {

Hope this works...
Best,
Luis

**Comment by lwjohnst86** [comment]
You need to update the r3 package. It won't fail if you use the updated
one. I updated since you took the course last time 😀
