### ISSUE TITLE
Wrong keyboard shortcut for git

### ISSUE THREAD

**Issue by AndersAskeland** [rostools/r-cubed-advanced#92]
Section 5.4 - Use ctrl + alt + m to open git pane (not ctrl + shift + m).

**Comment by AndersAskeland** [comment]
Seems like this is present throughout (at least chapter 5).

**Comment by AndersAskeland** [comment]
The shortcut for roxygen is also wrong (ctrl + shift + p). Is this something that happens automatically @lwjohnst86 ?

**Comment by lwjohnst86** [comment]
Yea, its through the `_variables.yml` file. I will work on this since I need to update the keybindings based on the changes I made in the intermediate course.
